#!/bin/bash
#additional option inside scenario
set -euf -o pipefail
D=$(dirname $BASH_SOURCE)
source $D/.functions
trap "handle_exit" EXIT


COMMAND="${1: }"




mongo_kill() {
    docker run --rm --net=host --name=mongo_client -it -v  `pwd`/tools/env:/script mongo:latest mongo localhost:27020/cards /script/killop.js
}

_infra_status() {
  $D/.resolve_dev_middleware_ports.sh
}

case "$COMMAND" in
  simple_ind_call)
    _yellow independent call of service
    remoteCall $host:$advice_port
    remoteCall $host:$fines_port
    remoteCall $host:$regular_port
    ;;

  env)
    _yellow start docker env
    docker-compose -f $D/env/docker-compose.yml up -d
    _infra_status
    ;;
  env_start)
    _yellow start docker env
    docker-compose -f $D/env/docker-compose.yml start
    _infra_status
    ;;
  mongo_fill)
    _yellowb 'fill mongo(repeat that a couple ot times)'
    docker run --rm --net=host --name=mongo_client -it -v  `pwd`/tools/env:/script mongo:latest mongo localhost:27020/cards /script/init.js
    docker run --rm --net=host --name=mongo_client -it -v  `pwd`/tools/env:/script mongo:latest mongo localhost:27020 --eval "var database='cards', collection='users', rows=2000000" /script/fill.js
    ;;
  mongo_kill_op)
    _yellowb kill all long running operation in mongo
    mongo_kill
    ;;
  env_down)
    _yellow down docker env
    docker-compose -f $D/env/docker-compose.yml down
    docker ps
    ;;
  env_stop)
    _yellow stop docker env
    docker-compose -f $D/env/docker-compose.yml stop
    docker ps
    ;;
  env_restart)
    _yellow stop docker env
    docker-compose -f $D/env/docker-compose.yml restart
    docker ps
    ;;
  *)
    echo "use command [simple_ind_call|simple_hub_call|load|light_load|heavy_load|env|env_stop|env_restart|env_down|mongo_fill|boot]"
    no_status
    _done
  ;;
esac

